GET http://localhost:8080/api/payments/7297cc7f-0b70-4bb6-ba6a-02f2d8b223a9
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 3,
  "value": "300 PLN"
}
