POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/eb595d34-a449-422c-b0ea-f59e1e7980ad
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/confirmed?pageSize=1&pageNumber=0
Accept: application/json
Content-Type: application/json
